### ISSUE TITLE
count(): Argument #1 ($value) must be of type Countable|array, int given in HGETALL

### ISSUE THREAD

**Issue by streamingsystems** [predis/predis#1309]
**Describe the bug**
Error thrown randomly for HGETALL command.

**To Reproduce**
We are unable to reproduce it at will, but this appears in our logs every few days. 

**Expected behavior**
We expect this error to not be thrown.

**Versions (please complete the following information):**
- Predis: 2.1.2
- PHP 8.2.6 
- Redis Server 6.2.12
- OS CentOS (Rocky)

**Code sample**
N/A

**Additional context**
 
count(): Argument #1 ($value) must be of type Countable|array, int given {"exception":"[object] (TypeError(code: 0): count(): Argument #1 ($value) must be of type Countable|array, int given at /home/ss/application/vendor/predis/predis/src/Command/Redis/HGETALL.php:37)
[stacktrace]
#0 /home/ss/application/vendor/predis/predis/src/Command/Redis/HGETALL.php(37): count(0)
#1 /home/ss/application/vendor/predis/predis/src/Client.php(359): Predis\\Command\\Redis\\HGETALL->parseResponse(0)
#2 /home/ss/application/vendor/predis/predis/src/Client.php(303): Predis\\Client->executeCommand(Object(Predis\\Command\\Redis\\HGETALL))

It look like in this function is called at random times for some random reason with $data is coming in as an int which is blowing up as count() is not expecting an int. 

public function parseResponse($data)
    {
        $result = [];

        for ($i = 0; $i < count($data); ++$i) {
            $result[$data[$i]] = $data[++$i];
        }

        return $result;
    }

I think changing it this would be a safe code change and solve this issue (since the code say that $data is array|null|string): 

public function parseResponse($data)
    {
        $result = [];

        if (is_countable($data)) {
           for ($i = 0; $i < count($data); ++$i) {
              $result[$data[$i]] = $data[++$i];
           }
        }

        return $result;
    }

Thanks!

**Comment by streamingsystems** [comment]
Done, reformatted.

**Comment by streamingsystems** [comment]
I did not want to open a new bug report on this as we are running the same system as above, but we saw this in our logs this morning. It the same type of item, Redis is returning 0 but the function on line 96 in ZRANGE.php is looking for an array | null | string, so it's throwing an error when an int is passed in.


count(): Argument #1 ($value) must be of type Countable|array, int given {"exception":"[object] (TypeError(code: 0): count(): Argument #1 ($value) must be of type Countable|array, int given at /home/ss/application/vendor/predis/predis/src/Command/Redis/ZRANGE.php:96)
[stacktrace]
#0 /home/ss/application/vendor/predis/predis/src/Command/Redis/ZRANGE.php(96): count(0)
#1 /home/ss/application/vendor/predis/predis/src/Client.php(391): Predis\\Command\\Redis\\ZRANGE->parseResponse(0)
#2 /home/ss/application/vendor/predis/predis/src/Client.php(335): Predis\\Client->executeCommand(Object(Predis\\Command\\Redis\\ZRANGE))

**Comment by vladvildanov** [comment]
@streamingsystems So, I tried to reproduce an issue by calling `HGETALL` command 10000 times and never hit 0. We need to understand is at a problem with Redis instance or somewhere in the client during response parsing phase. 

In our client there's an example how to create a debuggable connection, so you can log every "raw" response from server, so we can figure out if it's a Redis server that sends incorrect response. Please, follow this example and start logging every response with timestamp, so we can debug it later:

https://github.com/predis/predis/blob/v2.x/examples/debuggable_connection.php

**Comment by vladvildanov** [comment]
@streamingsystems Attach log file here when it's ready

**Comment by streamingsystems** [comment]
Hi All,

I don't have any way to reproduce it, but every few days this shows up in our Laravel logs and it just showed up again. We have many thousands of requests going through redis all day every day. It seems like every once in a while Redis returns a value that is not compatible:

worker.ERROR: count(): Argument #1 ($value) must be of type Countable|array, int given {"exception":"[object] (TypeError(code: 0): count(): Argument #1 ($value) must 
be of type Countable|array, int given at /home/ss/application/vendor/predis/predis/src/Command/Redis/ZRANGE.php:96)
[stacktrace]
#0 /home/ss/application/vendor/predis/predis/src/Command/Redis/ZRANGE.php(96): count(0)
#1 /home/ss/application/vendor/predis/predis/src/Client.php(391): Predis\\Command\\Redis\\ZRANGE->parseResponse(0)

**Comment by vladvildanov** [comment]
@streamingsystems Hi! As I mentioned, we need you to setup debuggable connection and store Redis server response in the separate log file (not laravel logs), I attached an example in the message above.

In other case, we can't reproduce this issue as well. Debuggable connection allows you to receive response from server before parsing. If you store this responses in separate file, we can define if it's an issue with library or in Redis instance itself
