### ISSUE TITLE
Random "php_network_getaddresses: getaddrinfo failed: Name or service not known" errors

### ISSUE THREAD

**Issue by RmK9** [predis/predis#789]
**Describe the bug**
Hi guys, we have been getting the above error about 50 times per day at random times. Using Laravel 9.21.6 and Predis v2.0.0 - happened with lower Laravel minor version and Predis 1.x versions as well. The weird thing is that everything actually works, we are using Redis for sessions and cache, no issues whatsoever. However, those errors just occur in the error log each day, really not sure why. We checked networking on the firewall and everything is always going through, never any issues.

**To Reproduce**
Not sure how to reproduce, use latest Laravel and Redis 6, connect using certificates.

**Expected behavior**
No random errors.

**Versions (please complete the following information):**
 - Predis v2.0.0
 - PHP 8.0.17
 - Redis Server 6.2.7
 - OS CentOS Stream 8 (4.18.0-365.el8.x86_64)
 - Laravel 9.21.6

**Code sample**
Will show the full stack trace of the error below (with the hostname anonymous - but it's showing the correct one originally).

```
 php_network_getaddresses: getaddrinfo failed: Name or service not known [tls://hostname:6379] {"Source server":"Prod","exception":"[object] (Predis\\Connection\\ConnectionException(code: 0): php_network_getaddresses: getaddrinfo failed: Name or service not known [tls://hostname:6379] at /var/www/vendor/predis/predis/src/Connection/AbstractConnection.php:132)
[stacktrace]
#0 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(109): Predis\\Connection\\AbstractConnection->onConnectionError('php_network_get...', 0)
#1 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(154): Predis\\Connection\\StreamConnection->createStreamSocket(Object(Predis\\Connection\\Parameters), 'tcp://cb-vm-db-...', 4)
#2 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(196): Predis\\Connection\\StreamConnection->tcpStreamInitializer(Object(Predis\\Connection\\Parameters))
#3 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(87): Predis\\Connection\\StreamConnection->tlsStreamInitializer(Object(Predis\\Connection\\Parameters))
#4 /var/www/vendor/predis/predis/src/Connection/AbstractConnection.php(81): Predis\\Connection\\StreamConnection->createResource()
#5 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(230): Predis\\Connection\\AbstractConnection->connect()
#6 /var/www/vendor/predis/predis/src/Connection/AbstractConnection.php(157): Predis\\Connection\\StreamConnection->connect()
#7 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(260): Predis\\Connection\\AbstractConnection->getResource()
#8 /var/www/vendor/predis/predis/src/Connection/StreamConnection.php(367): Predis\\Connection\\StreamConnection->write('*2\\r\\n$3\\r\\nGET\\r\\n$6...')
#9 /var/www/vendor/predis/predis/src/Connection/AbstractConnection.php(110): Predis\\Connection\\StreamConnection->writeRequest(Object(Predis\\Command\\Redis\\GET))
#10 /var/www/vendor/predis/predis/src/Client.php(316): Predis\\Connection\\AbstractConnection->executeCommand(Object(Predis\\Command\\Redis\\GET))
#11 /var/www/vendor/predis/predis/src/Client.php(299): Predis\\Client->executeCommand(Object(Predis\\Command\\Redis\\GET))
#12 /var/www/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(116): Predis\\Client->__call('get', Array)
#13 /var/www/vendor/laravel/framework/src/Illuminate/Redis/Connections/Connection.php(216): Illuminate\\Redis\\Connections\\Connection->command('get', Array)
#14 /var/www/vendor/laravel/framework/src/Illuminate/Cache/RedisStore.php(62): Illuminate\\Redis\\Connections\\Connection->__call('get', Array)
#15 /var/www/vendor/laravel/framework/src/Illuminate/Cache/Repository.php(97): Illuminate\\Cache\\RedisStore->get('KbHnj0CLlBYX8pm...')
#16 /var/www/vendor/laravel/framework/src/Illuminate/Session/CacheBasedSessionHandler.php(64): Illuminate\\Cache\\Repository->get('KbHnj0CLlBYX8pm...', '')
#17 /var/www/vendor/laravel/framework/src/Illuminate/Session/Store.php(110): Illuminate\\Session\\CacheBasedSessionHandler->read('KbHnj0CLlBYX8pm...')
#18 /var/www/vendor/laravel/framework/src/Illuminate/Session/Store.php(98): Illuminate\\Session\\Store->readFromHandler()
#19 /var/www/vendor/laravel/framework/src/Illuminate/Session/Store.php(82): Illuminate\\Session\\Store->loadSession()
#20 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(147): Illuminate\\Session\\Store->start()
#21 /var/www/vendor/laravel/framework/src/Illuminate/Support/helpers.php(302): Illuminate\\Session\\Middleware\\StartSession->Illuminate\\Session\\Middleware\\{closure}(Object(Illuminate\\Session\\Store))
#22 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(148): tap(Object(Illuminate\\Session\\Store), Object(Closure))
#23 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(116): Illuminate\\Session\\Middleware\\StartSession->startSession(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store))
#24 /var/www/vendor/laravel/framework/src/Illuminate/Session/Middleware/StartSession.php(64): Illuminate\\Session\\Middleware\\StartSession->handleStatefulRequest(Object(Illuminate\\Http\\Request), Object(Illuminate\\Session\\Store), Object(Closure))
#25 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Session\\Middleware\\StartSession->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#26 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/AddQueuedCookiesToResponse.php(37): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#27 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\AddQueuedCookiesToResponse->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#28 /var/www/vendor/laravel/framework/src/Illuminate/Cookie/Middleware/EncryptCookies.php(67): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#29 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Cookie\\Middleware\\EncryptCookies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#30 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#31 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(726): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#32 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(703): Illuminate\\Routing\\Router->runRouteWithinStack(Object(Illuminate\\Routing\\Route), Object(Illuminate\\Http\\Request))
#33 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(667): Illuminate\\Routing\\Router->runRoute(Object(Illuminate\\Http\\Request), Object(Illuminate\\Routing\\Route))
#34 /var/www/vendor/laravel/framework/src/Illuminate/Routing/Router.php(656): Illuminate\\Routing\\Router->dispatchToRoute(Object(Illuminate\\Http\\Request))
#35 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(167): Illuminate\\Routing\\Router->dispatch(Object(Illuminate\\Http\\Request))
#36 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(141): Illuminate\\Foundation\\Http\\Kernel->Illuminate\\Foundation\\Http\\{closure}(Object(Illuminate\\Http\\Request))
#37 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#38 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ConvertEmptyStringsToNull.php(31): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#39 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ConvertEmptyStringsToNull->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#40 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TransformsRequest.php(21): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#41 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/TrimStrings.php(40): Illuminate\\Foundation\\Http\\Middleware\\TransformsRequest->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#42 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\TrimStrings->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#43 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/ValidatePostSize.php(27): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#44 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\ValidatePostSize->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#45 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Middleware/PreventRequestsDuringMaintenance.php(86): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#46 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Foundation\\Http\\Middleware\\PreventRequestsDuringMaintenance->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#47 /var/www/vendor/fruitcake/laravel-cors/src/HandleCors.php(38): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#48 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Fruitcake\\Cors\\HandleCors->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#49 /var/www/vendor/laravel/framework/src/Illuminate/Http/Middleware/TrustProxies.php(39): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#50 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(180): Illuminate\\Http\\Middleware\\TrustProxies->handle(Object(Illuminate\\Http\\Request), Object(Closure))
#51 /var/www/vendor/laravel/framework/src/Illuminate/Pipeline/Pipeline.php(116): Illuminate\\Pipeline\\Pipeline->Illuminate\\Pipeline\\{closure}(Object(Illuminate\\Http\\Request))
#52 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(142): Illuminate\\Pipeline\\Pipeline->then(Object(Closure))
#53 /var/www/vendor/laravel/framework/src/Illuminate/Foundation/Http/Kernel.php(111): Illuminate\\Foundation\\Http\\Kernel->sendRequestThroughRouter(Object(Illuminate\\Http\\Request))
#54 /var/www/public/index.php(52): Illuminate\\Foundation\\Http\\Kernel->handle(Object(Illuminate\\Http\\Request))
#55 {main}
"} 
```

Would appreciate any feedback, thank you!

**Comment by tillkruss** [comment]
That comes from PHP networking layer. I'd ask about it on SO.
